### ISSUE TITLE
a strange question when testing TransE

### ISSUE THREAD

**Issue by ShellingFord221** [thunlp/KB2E#62]
I want to predict head by tail-relation, but nearly all the results are entities mentioned in tail's position (i.e. the most right of a triple), and the relation seems doesn't work (e.g. I want to predict the book written by A, the answer given by transE is B, another writter, other than a book.) Shouldn't the results are nearly all in head's position? Why did this happen?

**Comment by Mrlyk423** [comment]
Maybe you can check if the vector of written is close to \vec(0)?

**Comment by ShellingFord221** [comment]
I have already checked the vector of written. It is not close to \vec(0). It is so strange.

**Comment by Mrlyk423** [comment]
I only met this problem when:
(1) The relation vector is closed to vec(0) such as "friends"
(2) I use tail+relation to predict head instead of tail-relation wrongly.
Maybe you can check if the training triple also has such problem or it's the only problem in dev/test set. Besides, you can check the vector of tail+relation to find why is still closed to original tail.

**Comment by liutianling** [comment]
@Mrlyk423 你好，刚开始接触表示学习，我想请问的是训练数据中都是　实体，实体，关系路径，
然后为他们进行编号(id)，那么训练得到的关系向量是整个关系路径的吗？还是怎么提取单一关系的向量？谢谢！

**Comment by weiyifanfan** [comment]
Why is the head entity much worse than the tail entity，when I have a test?
